version: '2'
services:
    mysql:
            #        network_mode: "bridge"
        environment:
              MYSQL_ROOT_PASSWORD: wtt@564
              MYSQL_USER: test
              MYSQL_PASS: wtt@564
        image: "mysql/mysql-server:5.7" 
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "./db:/var/lib/mysql"
              #            - "./conf/my.cnf:/etc/my.cnf"
            - "./init:/docker-entrypoint-initdb.d/"
        ports:
            - "13306:3306"
